### ISSUE TITLE
Write a document on import cluster API

### ISSUE THREAD

**Issue by qiujian16** [open-cluster-management/website#481]
Add document on how to import a cluster provisioned by cluster api.

reference link: https://deepwiki.com/search/importer_0d988e12-b7e5-46f0-a616-52101084dd6c#3

doc to update: https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/blob/main/content/en/docs/getting-started/installation/register-a-cluster.md

steps to import a cluster provisioned by cluster-api:

prerequisite
- capi provider is installed on the hub cluster.
- hub cluster is able to access the provisioned capi cluster.
- Enable the ClusterImporter feature gates on the ClusterManager
- Bind the CAPI manager permission to the registration controller
- ensure the existence of cluster-info configmap

To import
- Create the CAPI cluster and the managedCluster on the hub
    - the name of the managedcluster MUST be the same as CAPI cluster's name and namespace.
```
kind: Cluster
metadata:
  name: capi-cluster
  namespace: capi-cluster
spec:
  ...
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: capi-cluster
spec:
  hubAcceptsClient: true
```

    - The managedCluster will be auto-imported when the CAPI cluster is provisioned.
